# Generated by Django 5.2.1 on 2025-07-29 18:30
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
from pathlib import Path


def populate(apps, schema_editor):
    pic_form = ["JPG", "PNG", "GIF", "TIFF", "WEBP", "SVG", "BMP", "HEIF"]
    vid_form = ["MP4", "AVI", "MOV", "WMV", "MKV", "WEBM"]

    save_path = str(f"{Path(__file__).resolve().parents[3]}\\saves")

    settings = {
        "save_loc": (True, save_path),
        "auto_items": (False, None, "Automatically go to items after scraping"),
        "absolute_links": (False, None, "Grab absolute links"),
        "related_links": (True, None, "Absolute links will be related to parent"),
        "relative_links": (False, None, "Grab relative links"),
        "grab_sleep": (True, 5),
        "save_sleep": (True, 10),
        "auto_update": (False, 10),
        "get_pages": (True),
        "parallel_processing": (True),
        "save_icons": (False),
    }

    Formats = apps.get_model('istos', 'Formats')
    for form in pic_form:
        obj = Formats(type = "pic", formName = form)
        obj.save()

    for form in vid_form:
        obj = Formats(type = "vid", formName = form)
        obj.save()

    Settings = apps.get_model('istos', "Settings")
    for key, value in settings.items():

        if isinstance(value, tuple):
            if len(value) == 2:
                on, addInfo = value
            elif len(value) == 3:
                on, addInfo, tip = value

            obj = Settings(settingName = key, on = on, addInfo = addInfo)
            obj.save()
        else:
            obj = Settings(settingName = key, on = value)
            obj.save()
    
    LinkType = apps.get_model('istos', 'LinkType')
    
    LinkType.objects.create(slug='media', name='Media')
    LinkType.objects.create(slug='links', name='Links')
    LinkType.objects.create(slug='video', name='Video')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('vid', 'vid'), ('pic', 'pic')], max_length=3)),
                ('formName', models.CharField(max_length=4)),
                ('formSave', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LinkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('site', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('dateGrabbed', models.DateField(default=django.utils.timezone.now)),
                ('lastUpdate', models.DateTimeField(null=True, default=None)),
                ('lastExtract', models.DateTimeField(null=True, default=None)),
                ('hasParent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='istos.link')),
                ('linkType', models.ManyToManyField(related_name='links', to='istos.linktype',)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settingName', models.CharField(max_length=100)),
                ('on', models.BooleanField(default=False)),
                ('addInfo', models.CharField(max_length=1000, null=True)),
                ('tip', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=100, null=True)),
                ('site', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('dateGrabbed', models.DateField(default=django.utils.timezone.now)),
                ('saved', models.BooleanField(default=False)),
                ('dateSaved', models.DateField(null=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='istos.link')),
                ('downloadBtn', models.BooleanField(default=False)),
            ],
        ),
        migrations.RunPython(populate)

    ]
