# Generated by Django 5.2.5 on 2025-08-22 23:21

from django.db import migrations, models

def populate(apps, schema_editor):
    rules = {
        ('pic', "I", "N", "C", "thumbnail"),
        ('pic', "I", "N", "C", "thumb")
    }

    Rules = apps.get_model('istos', 'Rules')
    for rule in rules:
        obj = Rules(type=rule[0], choice1=rule[1], choice2=rule[2], choice3=rule[3], text=rule[4])
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('istos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('vid', 'vid'), ('pic', 'pic'), ('abs', 'abs'), ('rel', 'rel')])),
                ('choice1', models.CharField(choices=[('LF', 'Look for'), ('I', 'Ignore')])),
                ('choice2', models.CharField(choices=[('T', 'Tag'), ('ID', 'Id'), ('C', 'Class'), ('N', 'Name')])),
                ('choice3', models.CharField(choices=[('BW', 'Begins with'), ('EW', 'Ends with'), ('C', 'Contains'), ('IS', 'Is')])),
                ('text', models.CharField(max_length=100)),
            ],
        ),
        migrations.RunPython(populate)
    ]
