# Generated by Django 5.2.5 on 2025-08-22 23:21

from django.db import migrations, models

from static.libs.test import db_test

def populate(apps, schema_editor):
    rules = {
        ('media', "exclude", "name", "contains", "icon"),
    }

    Rules = apps.get_model('istos', 'Rules')
    for rule in rules:
        obj = Rules(rule_type=rule[0], action_choice=rule[1], selector_type=rule[2], match_type=rule[3], text=rule[4])
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('istos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on', models.BooleanField(default=True)),
                ('rule_type', models.CharField(choices=[("media", "MEDIA"),("links", "LINKS")])),
                ('action_choice', models.CharField(choices=[("include", "INCLUDE"),("exclude", "EXCLUDE")])),
                ('selector_type', models.CharField(choices=[("tag", "TAG"),("id", "ID"),("class", "CLASS"),("name", "NAME")])),
                ('match_type', models.CharField(choices=[("begins with", "BEGINS WITH"),("ends with", "ENDS WITH"),("contains", "CONTAINS"),("is", "IS")])),
                ('text', models.CharField(max_length=100)),
            ],
        ),
        migrations.RunPython(populate),
        migrations.RunPython(db_test.populate)
    ]
