# Generated by Django 5.2.5 on 2025-12-30 04:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istos', '0002_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('scrape_type', models.CharField(choices=[('scrape', 'Scrape'), ('update', 'Update'), ('extraction', 'Extraction')])),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('linkType', models.ManyToManyField(related_name='links', to='istos.linktype')),
                ('currIndex', models.IntegerField(null=True))
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='pages',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='formats',
            name='type',
            field=models.CharField(choices=[('vid', 'Vid'), ('pic', 'Pic')], max_length=3),
        ),
        migrations.AlterField(
            model_name='link',
            name='linkType',
            field=models.ManyToManyField(related_name='link_type', to='istos.linktype'),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='linkType',
            field=models.ManyToManyField(related_name='scrape_link_type', to='istos.linktype'),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('paused', 'Paused'), ('failed', 'Failed')], default='queued'),
        ),
    ]
